# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

name: conda-pgm-env
dependencies:
  # build env
  - python=3.12
  - pip
  - scikit-build-core
  # build deps
  - libboost-headers
  - eigen
  - nlohmann_json
  - msgpack-cxx
  - numpy
  - cmake
  - ninja
  # test deps
  - pytest
  - pytest-cov
  - msgpack-python
