# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

changelog:
  exclude:
    labels:
      - github-actions
    authors:
      - dependabot
  categories:
    - title: Features and improvements
      labels:
        - feature
        - improvement
    - title: Bug fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
