# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

# MD001/heading-increment : Heading levels should only increment by one level at a time : https://github.com/DavidAnson/markdownlint/blob/v0.37.4/doc/md001.md
MD001: false

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.37.4/doc/md013.md
MD013: false
  # # Number of characters
  # line_length: 80
  # # Number of characters for headings
  # heading_line_length: 80
  # # Number of characters for code blocks
  # code_block_line_length: 80
  # # Include code blocks
  # code_blocks: true
  # # Include tables
  # tables: true
  # # Include headings
  # headings: true
  # # Strict length checking
  # strict: false
  # # Stern length checking
  # stern: false

# MD024/no-duplicate-heading : Multiple headings with the same content : https://github.com/DavidAnson/markdownlint/blob/v0.37.4/doc/md024.md
MD024: false
