# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

repos:
  - repo: local
    hooks:
      - id: reuse
        name: reuse
        entry: uv run --frozen reuse lint
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: uv run --frozen pytest
        language: system
        pass_filenames: false
        types_or: [ python, c++, c ]
      - id: ruff-format
        name: ruff-format
        entry: uv run --frozen ruff format
        language: system
        pass_filenames: false
        types: [ python ]
      - id: ruff-check
        name: ruff-check
        entry: uv run --frozen ruff check
        language: system
        pass_filenames: false
        types: [ python ]
      - id: mypy
        name: mypy
        entry: uv run --frozen mypy .
        language: system
        pass_filenames: false
        types: [ python ]
      - id: clang-format
        name: clang-format
        entry: uv run --frozen clang-format -style=file -i
        language: system
        pass_filenames: true
        types_or: [ c++, c ]
      - id: gersemi
        name: cmake-linter
        alias: cmake-linter
        entry: uv run --frozen gersemi -i --warnings-as-errors
        language: system
        pass_filenames: true
        types: [ cmake ]
  - repo: https://github.com/igorshubovych/markdownlint-cli  # outside pypi 
    rev: v0.49.1
    hooks:
      - id: markdownlint
        args: ["--fix"]
  # format .json and .jsonc files
  - repo: https://github.com/biomejs/pre-commit  # outside pypi 
    rev: v2.5.7
    hooks:
      # configuration is located in biome.jsonc
      - id: biome-format
        name: biome-format
