# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
  jobs:
    post_install:
      # Build package with doc requirements from pyproject.optional-dependencies
      - pip install --verbose --editable .[doc]
      # remove API DLL define in header
      - find power_grid_model_c/power_grid_model_c/include -name *.h -exec sed -i -r "s/#define PGM.*//g" {} \;
      - find power_grid_model_c/power_grid_model_c/include -name *.h -exec sed -i -r "s/PGM_API //g" {} \;
      # build doxygen for C header
      - cd docs/doxygen && doxygen && cd ../..
      # build class and package diagrams
      - pyreverse --no-standalone -o dot src/power_grid_model
      - ccomps -x classes.dot | dot -Grankdir=LR -Nfontsize=13 -Efontsize=13 | gvpack -m100 -array_l1 | neato -n2 -Tsvg -o docs/_static/classes.svg
      - dot packages.dot -Grankdir=TD -Nfontsize=13 -Efontsize=13 -Tsvg -o docs/_static/packages.svg
      - rm packages.dot classes.dot
      # download support and contribution
      - git clone https://github.com/PowerGridModel/.github --depth 1 --branch main pgm_org_github
      - mv RELEASE.md SUPPORT.md SECURITY.md CITATION.md docs/release_and_support/
      - mv GOVERNANCE.md CONTRIBUTING.md CODE_OF_CONDUCT.md docs/contribution/
      # fix links
      - find docs/release_and_support -name "*.md" -exec sed -i -r "s|./CONTRIBUTING.md|../contribution/CONTRIBUTING.md|g" {} \;
